### ISSUE TITLE
No test results uploaded

### ISSUE THREAD

**Issue by PhilBroderickCrezco** [buildkite/test-collector-dotnet#61]
I'm new to Buildkite and attempting to use this package with a very simple .NET test project with 1 test that just has `Assert.True(true)` (for simplicity).

I've added this package to my test project (see below `csproj`) and configured a test suite + added the `BUILDKITE_ANALYTICS_TOKEN` environment variable to my `pipeline.yml`, but I'm not seeing any results in the test suite. 

Csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Buildkite.TestAnalytics.Xunit" Version="0.1.1" />
        <PackageReference Include="coverlet.collector" Version="6.0.2"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0"/>
        <PackageReference Include="xunit" Version="2.9.2"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

</Project>

```

`pipeline.yml`:
```yaml
env:
  BUILDKITE_ANALYTICS_TOKEN: <TEST_SUITE_TOKEN>

steps:
  - label: ":dotnet: Test"
    key: "test"
    command: dotnet test Tests.csproj
    plugins:
      - docker:
          image: mcr.microsoft.com/dotnet/sdk:9.0
          propagate-environment: true
```

Is there anything I'm missing? I've been able to upload the test results in other formats (`junit`/`xml`) but would like to use this simpler configuration if possible. Is there anyway to debug what is going on with the test upload? I've tried this locally with the correct environment variables set and not having any luck.
